#!/bin/bash

groups=()
groups=( "${groups[@]}" "# Question faciles" )
c=0

q1="$1"
q2="$2"
q3="$3"
q4="$4"
q5="$5"

for i in interro/easy/{$q1,$q2}.md; do
	(( c = c+1 ))
	groups=( "${groups[@]}" "## Question $c" )
	groups=( "${groups[@]}" "$(cat "$i")" )
	groups=( "${groups[@]}" "" )
	groups=( "${groups[@]}" "" )
	groups=( "${groups[@]}" "" )
	groups=( "${groups[@]}" "" )
done

groups=( "${groups[@]}" "# Question moyennes" )

for i in interro/medium/{$q3,$q4}.md; do
	(( c = c+1 ))
	groups=( "${groups[@]}" "## Question $c" )
	groups=( "${groups[@]}" "$(cat "$i")" )
	groups=( "${groups[@]}" "" )
	groups=( "${groups[@]}" "" )
	groups=( "${groups[@]}" "" )
	groups=( "${groups[@]}" "" )
done

groups=( "${groups[@]}" "# Question dure" )

for i in interro/hard/$q5.md; do
	(( c = c+1 ))
	groups=( "${groups[@]}" "## Question $c" )
	groups=( "${groups[@]}" "$(cat "$i")" )
	groups=( "${groups[@]}" "" )
	groups=( "${groups[@]}" "" )
	groups=( "${groups[@]}" "" )
	groups=( "${groups[@]}" "" )
done

for el in "${groups[@]}"; do
	echo "${el}"
	echo
done
