#!/bin/bash

groups=()
groups=( "${groups[@]}" "**Nom** : __________________________________" )

groups=( "${groups[@]}" "# Questions à 1 point" )
c=0

q1="$1"
q2="$2"
q3="$3"
q4="$4"
q5="$5"

for i in interro/easy/{$q1,$q2}.md; do
	(( c = c+1 ))
	groups=( "${groups[@]}" "## Question $c" )
	groups=( "${groups[@]}" "$(cat "$i")" )
	groups=( "${groups[@]}" "" )
	groups=( "${groups[@]}" "" )
	groups=( "${groups[@]}" "" )
	groups=( "${groups[@]}" "" )
done

groups=( "${groups[@]}" "# Questions à 2 points" )

for i in interro/medium/{$q3,$q4}.md; do
	(( c = c+1 ))
	groups=( "${groups[@]}" "## Question $c" )
	groups=( "${groups[@]}" "$(cat "$i")" )
	groups=( "${groups[@]}" "" )
	groups=( "${groups[@]}" "" )
	groups=( "${groups[@]}" "" )
	groups=( "${groups[@]}" "" )
done

groups=( "${groups[@]}" "<p style='page-break-before: always'></p>" )
groups=( "${groups[@]}" "# Question à 4 points" )

for i in interro/hard/$q5.md; do
	(( c = c+1 ))
	groups=( "${groups[@]}" "## Question $c" )
	groups=( "${groups[@]}" "$(cat "$i")" )
	groups=( "${groups[@]}" "" )
	groups=( "${groups[@]}" "" )
	groups=( "${groups[@]}" "" )
	groups=( "${groups[@]}" "" )
done

for el in "${groups[@]}"; do
	echo "${el}"
	echo
done
