#!/bin/bash

groups=()
groups=( "${groups[@]}" "**Nom** : __________________________________" )

c=0

q1="$1"
q2="$2"
q3="$3"
q4="$4"
q5="$5"

for i in interro/easy/{$q1,$q2}.md; do
	(( c = c+1 ))
	groups=( "${groups[@]}" "#### Question $c (1 point)" )
	groups=( "${groups[@]}" "$(cat "$i")" )
	groups=( "${groups[@]}" "" )
	groups=( "${groups[@]}" "" )
	groups=( "${groups[@]}" "" )
	groups=( "${groups[@]}" "" )
done

for i in interro/medium/{$q3,$q4}.md; do
	(( c = c+1 ))
	groups=( "${groups[@]}" "#### Question $c (2 points)" )
	groups=( "${groups[@]}" "$(cat "$i")" )
	groups=( "${groups[@]}" "" )
	groups=( "${groups[@]}" "" )
	groups=( "${groups[@]}" "" )
	groups=( "${groups[@]}" "" )
done

groups=( "${groups[@]}" "<p style='page-break-before: always'></p>" )

for i in interro/hard/$q5.md; do
	(( c = c+1 ))
	groups=( "${groups[@]}" "#### Question $c (4 points)" )
	groups=( "${groups[@]}" "$(cat "$i")" )
	groups=( "${groups[@]}" "" )
	groups=( "${groups[@]}" "" )
	groups=( "${groups[@]}" "" )
	groups=( "${groups[@]}" "" )
done

groups=( "${groups[@]}" "<p style='page-break-before: always'></p>" )

for el in "${groups[@]}"; do
	echo "${el}"
	echo
done
